DECLARE
	variableOne VARCHAR2(100);
	variableTwo VARCHAR2(100);
--UNSURE IF SEMI-COLON IS NECESSARY HERE
BEGIN SCHEMA_NAME.PACKAGE_NAME.PROCEDURE_NAME(variableOne, variableTwo);
	DBMS_OUTPUT.PUT_LINE(variableOne);
	DBMS_OUTPUT.PUT_LINE(variableTwo);
END;
