DECLARE 
	count_variable NUMBER;
	CURSOR part_names IS 
		SELECT PARTITION_NAME FROM DBA_TAB_PARTITIONS
		WHERE TABLE_OWNER = 'OWNER_AS_STRING'
		AND TABLE_NAME = 'NAME_OF_TABLE_AS_STRING';
BEGIN
	FOR part_name IN part_names LOOP

		EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM OWNER_AS_STRING.NAME_OF_TABLE_AS_STRING PARTITION (' || part_name.PARTITION_NAME ||')' INTO count_variable;
	END LOOP
END;
